### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by kluen**

### CODE REVIEW

**Comment by kluen** [comment]
@loctvl842 Hi, I saw that you are closing most PRs. Just to understand: Are you not interested in outside contributions?

**Comment by loctvl842** [comment]
Yes I would love to. Sorry for this. But I want bigger contribution. For example, new highlight groups. Thanks for telling me. I appreciate that a lot.

**Comment by kluen** [comment]
Ok, I understand, bigger contributions would be great.
But regarding the smaller ones, such as this one: Are you going to leave the typo in, or should we re-open this?

**Comment by loctvl842** [comment]
Oh I fixed it, but recently I used git reset to handle `release` so the typo come back. Thanks a lot for reminding me.

**Comment by loctvl842** [comment]
> But regarding the smaller ones, such as this one: Are you going to leave the typo in, or should we re-open this?

Don't worry about this. I'll fix as soon as possible if any problem happen.

**Comment by kluen** [comment]
Alright, fair enough. :)

**Pull request closed without merging**
