### PR TITLE
colourscheme override

### PR DESCRIPTION
**Pull request by Red-M**
This should complete #106 
Please let me know if anything needs to be done for this and I can add that as required.

I have tested this and it works as expected, one caveat is that changing filter or colorscheme will not necessarily change the colours as it is possible to change the base colours from this method.

### CODE REVIEW

**Comment by Red-M** [comment]
I've tested this further with [my own fork to merge this and another MR I've submitted](https://github.com/Red-M/monokai-pro.nvim/tree/master) plus [my own config](https://github.com/Red-M/dotfiles) and it works really well to allow me to override things in the theme without having to make changes upstream. This completely removes the need for me to maintain a fork to make changes and is much easier to deal with for everyone IMO.

**Comment by loctvl842** [comment]
Thx a lot. Can you edit the `monokai-pro/config.lua` and README.md.

A clearer example showcasing the overrideScheme is preferable

**Comment by Red-M** [comment]
That should provide such an example, if an image is required, please let me know.

**Comment by loctvl842** [comment]
That's nice. Thanks.

**Pull request merged**
